# EatFit24 - Development Docker Compose
# Extends production configuration with development-specific settings
#
# Usage:
#   1. Create .env.local from .env.example
#   2. Start services: docker compose -f compose.yml -f compose.dev.yml --env-file .env.local up -d
#
# This file overrides production settings for local development:
# - Uses local.py settings (DEBUG=True)
# - Adds volume mounts for live code reloading
# - Loads environment variables from .env.local
# - No hardcoded secrets/tokens

services:
  # Django Backend API - Development Configuration
  backend:
    env_file:
      - .env.local
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DEBUG=True
      - WEBAPP_DEBUG_MODE_ENABLED=True
    volumes:
      # Add backend code as volume for live reloading
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
      - ./backend/logs:/app/logs
      - backend_venv:/app/.venv # Protect Docker-managed venv from host mount
    # Override healthcheck to use 127.0.0.1 (more reliable than localhost in containers)
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8000/health/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: >
      sh -c "
        /app/.venv/bin/python manage.py migrate &&
        /app/.venv/bin/python manage.py runserver 0.0.0.0:8000
      "

  # Celery Worker - Development Configuration
  celery-worker:
    env_file:
      - .env.local
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DEBUG=True
      - WEBAPP_DEBUG_MODE_ENABLED=True
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
      - ./backend/media:/app/media
      - backend_venv:/app/.venv # Protect Docker-managed venv from host mount

  # Celery Beat - Development Configuration
  celery-beat:
    env_file:
      - .env.local
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DEBUG=True
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
      - backend_venv:/app/.venv # Protect Docker-managed venv from host mount

  # Telegram Bot - Development Configuration
  bot:
    env_file:
      - .env.local
    environment:
      - DEBUG=True
    volumes:
      - ./bot:/app
      - ./bot/logs:/app/logs
      - bot_venv:/app/.venv # Protect Docker-managed venv from host mount

  # Database - Ensure it uses .env.local
  db:
    env_file:
      - .env.local

  # Redis - Ensure it uses .env.local
  redis:
    env_file:
      - .env.local

# Named volumes for development
volumes:
  backend_venv: # Isolate backend's uv-managed venv
  bot_venv: # Isolate bot's uv-managed venv
