# Generated by Django 5.2.7 on 2025-10-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("weight_loss", "Похудение"),
                    ("maintenance", "Поддержание веса"),
                    ("weight_gain", "Набор массы"),
                ],
                default="maintenance",
                help_text="Цель по весу: похудение, поддержание или набор массы",
                max_length=20,
                verbose_name="Цель",
            ),
        ),
    ]
