# Generated by Django 5.2.7 on 2025-11-06 04:26

from django.db import migrations, models


def remove_duplicate_emails(apps, schema_editor):
    """
    Remove duplicate emails before adding unique constraint.
    Keep the oldest user for each email.
    """
    User = apps.get_model('auth', 'User')
    db_alias = schema_editor.connection.alias

    # Find duplicate emails
    from django.db.models import Count
    duplicates = (
        User.objects.using(db_alias)
        .values('email')
        .annotate(count=Count('id'))
        .filter(count__gt=1, email__isnull=False)
        .exclude(email='')
    )

    for dup in duplicates:
        email = dup['email']
        users = User.objects.using(db_alias).filter(email=email).order_by('date_joined')

        # Keep first (oldest) user, delete others
        users_to_delete = users[1:]
        for user in users_to_delete:
            # Optionally: migrate data before deletion
            user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_goal_type"),
        ("auth", "__latest__"),  # Depend on auth app for User model
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_emails,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            # Add unique index for email (SQLite doesn't support ALTER TABLE ADD CONSTRAINT)
            sql="CREATE UNIQUE INDEX auth_user_email_unique ON auth_user(email);",
            reverse_sql="DROP INDEX IF EXISTS auth_user_email_unique;",
        ),
    ]
