# Generated by Django 5.2.8 on 2025-11-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_email_verification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailverificationtoken",
            new_name="users_email_token_c6eae7_idx",
            old_name="users_email_token_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverificationtoken",
            new_name="users_email_user_id_0476c8_idx",
            old_name="users_email_user_used_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverificationtoken",
            new_name="users_email_expires_7cc044_idx",
            old_name="users_email_expires_idx",
        ),
        migrations.AddField(
            model_name="profile",
            name="target_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Желаемый вес в килограммах",
                max_digits=5,
                null=True,
                verbose_name="Целевой вес (кг)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text="Часовой пояс пользователя (например, Europe/Moscow, Asia/Yekaterinburg)",
                max_length=50,
                null=True,
                verbose_name="Часовой пояс",
            ),
        ),
    ]
