# Generated by Django 5.2.8 on 2025-11-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0005_rename_users_email_token_idx_users_email_token_c6eae7_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ai_recommendations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Полный JSON с рекомендациями от AI: анализ, цели, изменения, тренировки, питание",
                verbose_name="AI рекомендации",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="current_body_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Вариант от 1 до 4",
                null=True,
                verbose_name="Текущий тип фигуры",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="goals",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список целей: weight_loss, remove_belly, tone_body и т.д.",
                verbose_name="Цели",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="health_restrictions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список ограничений: back_problems, joint_problems и т.д.",
                verbose_name="Ограничения по здоровью",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ideal_body_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Вариант от 1 до 4",
                null=True,
                verbose_name="Идеальный тип фигуры",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recommended_calories_max",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Калории максимум (ккал/день)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recommended_calories_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Калории минимум (ккал/день)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recommended_carbs_max",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Углеводы максимум (г)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recommended_carbs_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Углеводы минимум (г)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recommended_fat_max",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Жиры максимум (г)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recommended_fat_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Жиры минимум (г)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recommended_protein_max",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Белок максимум (г)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recommended_protein_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Белок минимум (г)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID пользователя в Telegram",
                null=True,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                help_text="@username пользователя в Telegram",
                max_length=255,
                null=True,
                verbose_name="Telegram Username",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="training_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Новичок — не тренируюсь / реже 1 раза в неделю"),
                    ("intermediate", "Средний — 2-3 тренировки в неделю"),
                    ("advanced", "Продвинутый — 4+ тренировки в неделю"),
                    ("home", "Домашний формат — тренируюсь дома"),
                ],
                max_length=20,
                null=True,
                verbose_name="Уровень тренированности",
            ),
        ),
    ]
