# Generated by Django 5.2.8 on 2025-12-06 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_add_avatar_validators_and_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="recommended_calories_max",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="recommended_calories_min",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="recommended_carbs_max",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="recommended_carbs_min",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="recommended_fat_max",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="recommended_fat_min",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="recommended_protein_max",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="recommended_protein_min",
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["telegram_id"], name="users_profi_telegra_2ee79a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["created_at"], name="users_profi_created_f60c54_idx"
            ),
        ),
    ]
