# Generated by Django 5.2.7 on 2025-11-05 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FREE", "Бесплатный"),
                            ("MONTHLY", "Месячный"),
                            ("YEARLY", "Годовой"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Название плана",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        max_length=100, verbose_name="Отображаемое название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цена (₽)",
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(default=0, verbose_name="Длительность (дней)"),
                ),
                (
                    "max_photos_per_day",
                    models.IntegerField(
                        default=3,
                        help_text="-1 = неограниченно",
                        verbose_name="Макс. фото в день",
                    ),
                ),
                (
                    "history_days",
                    models.IntegerField(
                        default=7,
                        help_text="-1 = неограниченно",
                        verbose_name="Хранение истории (дней)",
                    ),
                ),
                (
                    "ai_recognition",
                    models.BooleanField(default=True, verbose_name="AI распознавание"),
                ),
                (
                    "advanced_stats",
                    models.BooleanField(
                        default=False, verbose_name="Расширенная статистика"
                    ),
                ),
                (
                    "priority_support",
                    models.BooleanField(
                        default=False, verbose_name="Приоритетная поддержка"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Тарифный план",
                "verbose_name_plural": "Тарифные планы",
                "db_table": "subscription_plans",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидание оплаты"),
                            ("WAITING_FOR_CAPTURE", "Ожидание подтверждения"),
                            ("SUCCEEDED", "Успешно"),
                            ("CANCELED", "Отменён"),
                            ("FAILED", "Ошибка"),
                            ("REFUNDED", "Возврат"),
                        ],
                        default="PENDING",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("YOOKASSA", "ЮKassa")],
                        default="YOOKASSA",
                        max_length=50,
                        verbose_name="Платёжный провайдер",
                    ),
                ),
                (
                    "yookassa_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="ID платежа ЮKassa",
                    ),
                ),
                (
                    "yookassa_payment_method_id",
                    models.CharField(
                        blank=True,
                        help_text="Для сохранения способа оплаты",
                        max_length=255,
                        null=True,
                        verbose_name="ID способа оплаты ЮKassa",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, verbose_name="Рекуррентный платёж"
                    ),
                ),
                (
                    "save_payment_method",
                    models.BooleanField(
                        default=True, verbose_name="Сохранить способ оплаты"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные данные"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма возврата"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "В обработке"),
                            ("SUCCEEDED", "Успешно"),
                            ("CANCELED", "Отменён"),
                        ],
                        default="PENDING",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "yookassa_refund_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="ID возврата ЮKassa",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Причина")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="billing.payment",
                        verbose_name="Платёж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Возврат",
                "verbose_name_plural": "Возвраты",
                "db_table": "refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "auto_renew",
                    models.BooleanField(default=False, verbose_name="Автопродление"),
                ),
                (
                    "yookassa_payment_method_id",
                    models.CharField(
                        blank=True,
                        help_text="Сохранённый способ оплаты для рекуррентных платежей",
                        max_length=255,
                        null=True,
                        verbose_name="ID способа оплаты ЮKassa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.subscriptionplan",
                        verbose_name="Тарифный план",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="billing.subscription",
                verbose_name="Подписка",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="billing.subscriptionplan",
                verbose_name="Тарифный план",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-created_at"], name="payments_created_26b056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_status_d621e5_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["yookassa_payment_id"], name="payments_yookass_ad8fbb_idx"
            ),
        ),
    ]
