# Generated by Django 5.2.8 on 2025-12-06 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_remove_dailyusage_unique_user_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["is_active", "end_date"], name="subscriptio_is_acti_867b85_idx"
            ),
        ),
    ]
