# Generated by Django 5.2.8 on 2025-12-06 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_subscription_subscriptio_is_acti_867b85_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="webhook_processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время обработки webhook (для idempotency)",
                null=True,
                verbose_name="Webhook обработан",
            ),
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="Тип события"),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="ID события YooKassa",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID платежа YooKassa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Получен"),
                            ("PROCESSING", "Обработка"),
                            ("SUCCESS", "Успешно"),
                            ("FAILED", "Ошибка"),
                            ("DUPLICATE", "Дубликат"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="Статус обработки",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Попытки обработки"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "raw_payload",
                    models.JSONField(default=dict, verbose_name="Сырые данные webhook"),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP клиента"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Получен"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обработан"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог webhook",
                "verbose_name_plural": "Логи webhook",
                "db_table": "webhook_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="webhook_log_created_5dbdab_idx"
                    ),
                    models.Index(
                        fields=["status"], name="webhook_log_status_58a1da_idx"
                    ),
                ],
            },
        ),
    ]
