# Generated by Django 5.2.8 on 2025-12-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_normalize_plan_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyusage",
            name="photo_ai_requests",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Сколько раз пользователь отправлял фото на распознавание за день",
                verbose_name="Количество фото-запросов к AI",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="webhook_processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Для идемпотентности: если webhook повторится — мы видим, что уже обработали",
                null=True,
                verbose_name="Webhook обработан",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="yookassa_payment_method_id",
            field=models.CharField(
                blank=True,
                help_text="Сохраняется при успешной оплате, если save_payment_method=True",
                max_length=255,
                null=True,
                verbose_name="ID способа оплаты ЮKassa",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="card_brand",
            field=models.CharField(
                blank=True,
                help_text="Visa, MasterCard, МИР и т.д.",
                max_length=50,
                null=True,
                verbose_name="Тип карты",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="card_mask",
            field=models.CharField(
                blank=True,
                help_text='Например: "•••• 1234"',
                max_length=20,
                null=True,
                verbose_name="Маска карты",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="code",
            field=models.CharField(
                help_text="Уникальный код для API: FREE, PRO_MONTHLY, PRO_YEARLY и т.д.",
                max_length=50,
                unique=True,
                verbose_name="Системный код",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="daily_photo_limit",
            field=models.IntegerField(
                blank=True,
                help_text="Null = безлимит",
                null=True,
                verbose_name="Лимит фото в день",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="is_test",
            field=models.BooleanField(
                default=False,
                help_text="Тестовый план для проверки live-платежей (только для админов)",
                verbose_name="Тестовый план",
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Получен"),
                    ("QUEUED", "В очереди"),
                    ("PROCESSING", "Обработка"),
                    ("SUCCESS", "Успешно"),
                    ("FAILED", "Ошибка"),
                    ("DUPLICATE", "Дубликат"),
                ],
                default="RECEIVED",
                max_length=20,
                verbose_name="Статус обработки",
            ),
        ),
    ]
