# Generated by Django 5.2.8 on 2025-12-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_add_billing_period_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooklog",
            name="provider_event_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Оригинальный event ID от YooKassa (uuid или id поле)",
                max_length=255,
                null=True,
                verbose_name="ID события от провайдера",
            ),
        ),
        migrations.AddField(
            model_name="webhooklog",
            name="trace_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Уникальный ID запроса для корреляции логов",
                max_length=36,
                null=True,
                verbose_name="Trace ID",
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="event_id",
            field=models.CharField(
                help_text="Уникальный ключ: provider_event_id или computed event_type:obj_id:obj_status",
                max_length=255,
                unique=True,
                verbose_name="Idempotency key",
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["trace_id"], name="webhook_log_trace_i_a4a529_idx"
            ),
        ),
    ]
