# Generated by Django 6.0.1 on 2026-01-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_add_trace_id_and_provider_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="old_price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Якорная цена для отображения скидки (например: было 4990₽)",
                null=True,
                verbose_name="Старая цена (₽)",
            ),
        ),
    ]
