# Generated by Django 5.2.7 on 2025-11-19 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="Уникальный ID пользователя в Telegram",
                        unique=True,
                        verbose_name="Telegram ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="@username пользователя (может отсутствовать)",
                        max_length=255,
                        null=True,
                        verbose_name="Telegram Username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Фамилия"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        default="ru",
                        help_text="Код языка пользователя (ru, en, etc.)",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли пользователь подписчиком Telegram Premium",
                        verbose_name="Telegram Premium",
                    ),
                ),
                (
                    "ai_test_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Прошел ли пользователь лид-магнит тест",
                        verbose_name="AI тест пройден",
                    ),
                ),
                (
                    "ai_test_answers",
                    models.JSONField(
                        blank=True,
                        help_text="JSON с ответами пользователя из лид-магнита",
                        null=True,
                        verbose_name="Ответы AI теста",
                    ),
                ),
                (
                    "recommended_calories",
                    models.IntegerField(
                        blank=True,
                        help_text="Калории в день (расчет из AI теста)",
                        null=True,
                        verbose_name="Рекомендованные калории",
                    ),
                ),
                (
                    "recommended_protein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Белки в граммах (расчет из AI теста)",
                        max_digits=6,
                        null=True,
                        verbose_name="Рекомендованные белки (г)",
                    ),
                ),
                (
                    "recommended_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Жиры в граммах (расчет из AI теста)",
                        max_digits=6,
                        null=True,
                        verbose_name="Рекомендованные жиры (г)",
                    ),
                ),
                (
                    "recommended_carbs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Углеводы в граммах (расчет из AI теста)",
                        max_digits=6,
                        null=True,
                        verbose_name="Рекомендованные углеводы (г)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь Django",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram пользователь",
                "verbose_name_plural": "Telegram пользователи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["telegram_id"], name="telegram_te_telegra_000672_idx"
                    ),
                    models.Index(
                        fields=["ai_test_completed"],
                        name="telegram_te_ai_test_69e019_idx",
                    ),
                ],
            },
        ),
    ]
