# Generated by Django 5.2.8 on 2025-11-21 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_client",
            field=models.BooleanField(
                default=False,
                help_text="Является ли пользователь клиентом (добавлен в список клиентов)",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddIndex(
            model_name="telegramuser",
            index=models.Index(
                fields=["is_client"], name="telegram_te_is_clie_c4959d_idx"
            ),
        ),
    ]
