# Generated by Django 5.2.8 on 2025-11-26 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0002_telegramuser_is_client_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalPlanSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Мужской"), ("female", "Женский")],
                        max_length=10,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        help_text="Возраст в годах (14-80)", verbose_name="Возраст"
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveSmallIntegerField(
                        help_text="Рост в сантиметрах (120-250)",
                        verbose_name="Рост (см)",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Вес в килограммах (30-300)",
                        max_digits=5,
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "target_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Желаемый вес в килограммах",
                        max_digits=5,
                        null=True,
                        verbose_name="Целевой вес (кг)",
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("sedentary", "Сидячий образ жизни"),
                            ("light", "Легкая активность"),
                            ("moderate", "Умеренная активность"),
                            ("active", "Активный образ жизни"),
                            ("very_active", "Очень активный образ жизни"),
                        ],
                        max_length=20,
                        verbose_name="Уровень активности",
                    ),
                ),
                (
                    "training_level",
                    models.CharField(
                        blank=True,
                        help_text="Например: beginner, intermediate, advanced, home",
                        max_length=32,
                        null=True,
                        verbose_name="Уровень тренированности",
                    ),
                ),
                (
                    "body_goals",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список целей: weight_loss, remove_belly, tone_body и т.д.",
                        verbose_name="Цели по телу",
                    ),
                ),
                (
                    "health_limitations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список ограничений: back_problems, joint_problems и т.д.",
                        verbose_name="Ограничения по здоровью",
                    ),
                ),
                (
                    "body_now_id",
                    models.PositiveSmallIntegerField(
                        verbose_name="ID текущего типа фигуры"
                    ),
                ),
                (
                    "body_now_label",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Описание текущего типа фигуры",
                    ),
                ),
                (
                    "body_now_file",
                    models.TextField(
                        help_text="Путь к файлу/изображению текущего типа фигуры",
                        verbose_name="Файл с текущим типом фигуры",
                    ),
                ),
                (
                    "body_ideal_id",
                    models.PositiveSmallIntegerField(
                        verbose_name="ID идеального типа фигуры"
                    ),
                ),
                (
                    "body_ideal_label",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Описание идеального типа фигуры",
                    ),
                ),
                (
                    "body_ideal_file",
                    models.TextField(
                        help_text="Путь к файлу/изображению идеального типа фигуры",
                        verbose_name="Файл с идеальным типом фигуры",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow",
                        help_text="Часовой пояс пользователя (например, Europe/Moscow)",
                        max_length=64,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "utc_offset_minutes",
                    models.IntegerField(
                        help_text="Смещение часового пояса от UTC в минутах",
                        verbose_name="Смещение UTC (минуты)",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда пользователь завершил опрос",
                        null=True,
                        verbose_name="Дата завершения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_plan_surveys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опрос Personal Plan",
                "verbose_name_plural": "Опросы Personal Plan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_text",
                    models.TextField(
                        help_text="Полный текст плана питания и тренировок от AI",
                        verbose_name="Текст плана от AI",
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        blank=True,
                        help_text="Модель AI, которая сгенерировала план (например, meta-llama/llama-3.1-70b-instruct)",
                        max_length=100,
                        null=True,
                        verbose_name="AI модель",
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True,
                        help_text="Версия промпта, использованного для генерации (например, v1.0)",
                        max_length=20,
                        null=True,
                        verbose_name="Версия промпта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        blank=True,
                        help_text="Опрос, на основе которого был сгенерирован план",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_plans",
                        to="telegram.personalplansurvey",
                        verbose_name="Опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Plan",
                "verbose_name_plural": "Personal Plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="personalplansurvey",
            index=models.Index(
                fields=["user", "completed_at"], name="telegram_pe_user_id_a81801_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalplansurvey",
            index=models.Index(
                fields=["created_at"], name="telegram_pe_created_2b80e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalplan",
            index=models.Index(
                fields=["user", "created_at"], name="telegram_pe_user_id_ccc125_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalplan",
            index=models.Index(
                fields=["survey"], name="telegram_pe_survey__f8f9dd_idx"
            ),
        ),
    ]
