# Generated by Django 6.0.1 on 2026-01-12 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_alter_personalplan_ai_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personalplan',
            constraint=models.UniqueConstraint(condition=models.Q(('survey__isnull', False)), fields=('user', 'survey'), name='unique_user_survey_plan'),
        ),
    ]
