# Generated by Django 5.2.7 on 2025-10-27 17:55

import apps.common.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Завтрак"),
                            ("LUNCH", "Обед"),
                            ("DINNER", "Ужин"),
                            ("SNACK", "Перекус"),
                        ],
                        max_length=10,
                        verbose_name="Тип приёма пищи",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приём пищи",
                "verbose_name_plural": "Приёмы пищи",
                "db_table": "nutrition_meals",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название блюда"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.common.storage.upload_to_food_photos,
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "grams",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Вес (граммы)",
                    ),
                ),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Калории",
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Белки (г)",
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Жиры (г)",
                    ),
                ),
                (
                    "carbohydrates",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Углеводы (г)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="nutrition.meal",
                        verbose_name="Приём пищи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блюдо",
                "verbose_name_plural": "Блюда",
                "db_table": "nutrition_food_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(500)],
                        verbose_name="Калории (цель)",
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Белки (г, цель)",
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Жиры (г, цель)",
                    ),
                ),
                (
                    "carbohydrates",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Углеводы (г, цель)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AUTO", "Автоматический расчет"),
                            ("MANUAL", "Ручной ввод"),
                        ],
                        default="AUTO",
                        max_length=10,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневная цель",
                "verbose_name_plural": "Дневные цели",
                "db_table": "nutrition_daily_goals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="nutrition_d_user_id_c89a9a_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["user", "date"], name="nutrition_m_user_id_be0d5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["date"], name="nutrition_m_date_35ada6_idx"),
        ),
    ]
