# Generated by Django 5.2.7 on 2025-11-06 04:18

import apps.common.storage
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.common.storage.upload_to_food_photos,
                validators=[
                    apps.common.validators.FileSizeValidator(max_mb=10),
                    apps.common.validators.ImageDimensionValidator(
                        max_height=4096, max_width=4096
                    ),
                ],
                verbose_name="Фотография",
            ),
        ),
    ]
