# Generated by Django 5.2.8 on 2026-01-07 12:37

import apps.common.storage
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0005_migrate_existing_photos"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="meal",
            new_name="nutrition_m_user_id_c8b69a_idx",
            old_name="nutrition_m_user_id_8a4f2e_idx",
        ),
        migrations.RenameIndex(
            model_name="mealphoto",
            new_name="nutrition_m_meal_id_9993db_idx",
            old_name="nutrition_m_meal_id_d3b1c2_idx",
        ),
        migrations.AlterField(
            model_name="meal",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.common.storage.upload_to_meal_photos,
                validators=[
                    apps.common.validators.FileSizeValidator(max_mb=10),
                    apps.common.validators.ImageDimensionValidator(max_height=4096, max_width=4096),
                ],
                verbose_name="Фотография приёма пищи (устаревшее)",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PROCESSING", "Обработка"),
                    ("COMPLETE", "Готово"),
                    ("FAILED", "Ошибка"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mealphoto",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Ожидание"),
                    ("PROCESSING", "Обработка"),
                    ("SUCCESS", "Успешно"),
                    ("FAILED", "Ошибка"),
                    ("CANCELLED", "Отменено"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Статус обработки",
            ),
        ),
    ]
