# Generated by Django 6.0.1 on 2026-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_rename_nutrition_m_user_id_8a4f2e_idx_nutrition_m_user_id_c8b69a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealphoto',
            name='error_code',
            field=models.CharField(blank=True, help_text='Структурированный код ошибки: UPSTREAM_TIMEOUT, INVALID_IMAGE, RATE_LIMIT, etc.', max_length=50, null=True, verbose_name='Код ошибки'),
        ),
    ]
