# Generated by Django 6.0.1 on 2026-01-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_add_error_code_to_mealphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_cancel_id', models.UUIDField(db_index=True, help_text='UUID генерируется на фронте для идемпотентности', unique=True, verbose_name='Идентификатор отмены (клиент)')),
                ('run_id', models.IntegerField(blank=True, help_text='Frontend run identifier', null=True, verbose_name='Run ID')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Сохраняет весь запрос для аудита: task_ids, meal_photo_ids, reason, etc.', verbose_name='Полный payload запроса')),
                ('cancelled_tasks', models.IntegerField(default=0, help_text='Количество отозванных Celery tasks', verbose_name='Отменено задач')),
                ('updated_photos', models.IntegerField(default=0, help_text='Количество MealPhoto обновлённых в CANCELLED', verbose_name='Обновлено фото')),
                ('noop', models.BooleanField(default=False, help_text='True если отменять было нечего (ранний cancel)', verbose_name='Noop')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancel_events', to='nutrition.meal', verbose_name='Приём пищи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие отмены',
                'verbose_name_plural': 'События отмены',
                'db_table': 'nutrition_cancel_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='nutrition_c_user_id_57c403_idx'), models.Index(fields=['client_cancel_id'], name='nutrition_c_client__885306_idx')],
            },
        ),
    ]
